env:
  es2021: true
extends: 
  - airbnb-base
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:  
  import/extensions: 0
  no-console: off
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
